users/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name ="home_app"
urlpatterns = [
    path(
        'panel/', 
        views.HomePage.as_view(),
        name = 'panel',
    ),
    path(
        'mixin/', 
        views.TemplatePruebaMixin.as_view(),
        name = 'mixin',
    ),
        
]

users/applications/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name ="users_app"
urlpatterns = [
    path(
        'register-user/', 
        views.UserRegisterView.as_view(),
        name = 'register_user',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name = 'user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name = 'user-logout',
    ),
    path(
        'update-password/', 
        views.UpdatePasswordView.as_view(),
        name = 'user-update',
    ),
    path(
        'verification/<pk>/', 
        views.UpdatePasswordView.as_view(),
        name = 'user-verification',
    ),

        
]

users/users/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    
]

users/applications/home/models.py
from django.db import models

# Create your models here.

users/applications/home/views.py
import datetime

from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from django.views.generic import(
    TemplateView
)
# Create your views here.


class FechaMixin(object):
    
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha']=datetime.datetime.now()
        return context
#LoginRequiredMixin validate if you is login or login_url redirect
class HomePage(LoginRequiredMixin,TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:user-login')




class TemplatePruebaMixin(TemplateView):
    template_name = "home/mixin.html"

users/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido {{user}}</h3>
    
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar Sesion</a></li>
        <li><a href="{% url 'users_app:user-update' %}">Actualizar datos</a></li>
    </ul>
</body>
</html>

users/templates/home/mixin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Mixin Prueba</h1>

</body>
</html>